#!/usr/bin/python3
""" Factor number """
from sys import argv
from math import sqrt


def open_file(file_name):
    """ open a file """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    factor = []
    for line in lines:
        factor.append(int(line))
    return factor

    """ factor of all test number """
def factor_and_test(n):
    for i in range(1, n):
        if n == ((n // i) * i):
            print(f"{n} = {n // i} * {i}")
            break

def fac_list(test):
    """ factor each number in the test """
    for i in test:
        factor_and_test(i)

if len(argv) == 2:
    fac_list(open_file(argv[1]))
